"""Initial migration

Revision ID: 14b3222961cf
Revises:
Create Date: 2025-01-07 03:02:37.860221

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "14b3222961cf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
